GLOBAL:
    LOG_LEVEL: 2
    GPU_INDICES:
    - 0
    RANDOM_SEED: 0
    ANOMALY_DETECTION: false
    FILTER_WARNINGS: true
    METHOD_TYPE: GaussianSplatting
    DATASET_TYPE: MipNeRF360
MODEL:
    SH_DEGREE: 3
RENDERER:
    USE_FUSED_COVARIANCE_COMPUTATION: true
    USE_FUSED_SH_CONVERSION: true
    SCALE_MODIFIER: 1.0
    DISABLE_SH0: false
    DISABLE_SH1: false
    DISABLE_SH2: false
    DISABLE_SH3: false
    USE_BAKED_COVARIANCE: false
TRAINING:
    LOAD_CHECKPOINT: null
    MODEL_NAME: 3dgs_garden
    NUM_ITERATIONS: 30_000
    RUN_VALIDATION: false
    DATA:
        PRELOADING_LEVEL: 2
        FIELDS: ['rgb', 'alpha']
        PRECOMPUTE_RAYS: false
        RAYS_TO_DEVICE: false
    BACKUP:
        FINAL_CHECKPOINT: true
        RENDER_TESTSET: true
        RENDER_TRAINSET: false
        RENDER_VALSET: false
        INTERMEDIATE_RENDERINGS: true
        VISUALIZE_ERRORS: false
        INTERVAL: -1
        TRAINING_STATE: false
    TIMING:
        ACTIVATE: false
        INCLUDE_DATALOADING_IN_TOTAL: true
        INCLUDE_PRETRAINING_IN_TOTAL: true
        INCLUDE_POSTTRAINING_IN_TOTAL: false
    WANDB:
        ACTIVATE: false
        ENTITY: null
        PROJECT: nerficg
        LOG_IMAGES: true
        INDEX_VALIDATION: -1
        INDEX_TRAINING: -1
        INTERVAL: 1000
        SWEEP_MODE:
            ACTIVE: false
            START_ITERATION: 999
            ITERATION_STRIDE: 1000
            NUM_IMAGES: -1
    WRITE_VRAM_STATS: false
    GUI:
        ACTIVATE: true
        RENDER_INTERVAL: 5
        GUI_STATUS_ENABLED: true
        GUI_STATUS_INTERVAL: 20
        SKIP_GUI_SETUP: false
        FPS_ROLLING_AVERAGE_SIZE: 100
    LEARNING_RATE_POSITION_INIT: 0.00016
    LEARNING_RATE_POSITION_FINAL: 1.6e-06
    LEARNING_RATE_POSITION_MAX_STEPS: 30_000
    LEARNING_RATE_FEATURE: 0.0025
    LEARNING_RATE_OPACITY: 0.025  # the 3dgs authors used 0.05 for the results in the paper
    LEARNING_RATE_SCALING: 0.005
    LEARNING_RATE_ROTATION: 0.001
    PERCENT_DENSE: 0.01
    OPACITY_RESET_INTERVAL: 3_000
    DENSIFY_START_ITERATION: 500
    DENSIFY_END_ITERATION: 15_000
    DENSIFICATION_INTERVAL: 100
    DENSIFY_GRAD_THRESHOLD: 0.0002
    LOSS:
        LAMBDA_L1: 0.8
        LAMBDA_DSSIM: 0.2
DATASET:
    PATH: dataset/mipnerf360/garden
    IMAGE_SCALE_FACTOR: 0.25
    NORMALIZE_CUBE: null
    NORMALIZE_RECENTER: false
    BACKGROUND_COLOR:
    - 0.0
    - 0.0
    - 0.0
    NEAR_PLANE: 0.01  # only used to construct the projection matrix as it is hardcoded in the rasterizer
    FAR_PLANE: 100.0  # only used to construct the projection matrix as it is hardcoded in the rasterizer
    TEST_STEP: 8
    APPLY_PCA: true
    APPLY_PCA_RESCALE: false
