GLOBAL:
    LOG_LEVEL: 2
    GPU_INDICES:
    - 0
    RANDOM_SEED: 0
    ANOMALY_DETECTION: false
    FILTER_WARNINGS: true
    METHOD_TYPE: InstantNGP
    DATASET_TYPE: NeRF
MODEL:
    SCALE: 0.5
    RESOLUTION: 128
    CENTER:
    - 0.0
    - 0.0
    - 0.0
    HASHGRID_N_LEVELS: 16
    HASHGRID_N_FEATURES_PER_LEVEL: 2
    HASHGRID_LOG2_SIZE: 19
    HASHGRID_BASE_RESOLUTION: 16
    HASHGRID_TARGET_RESOLUTION: 2048
    N_DENSITY_OUTPUT_FEATURES: 16
    N_DENSITY_NEURONS: 64
    N_DENSITY_LAYERS: 1
    DIR_SH_ENCODING_DEGREE: 4
    N_COLOR_NEURONS: 64
    N_COLOR_LAYERS: 2
    ENABLE_JIT_FUSION: true
RENDERER:
    MAX_SAMPLES: 1024
    EXPONENTIAL_STEPS: false
    DENSITY_THRESHOLD: 0.01
TRAINING:
    LOAD_CHECKPOINT: null
    MODEL_NAME: ingp_lego
    NUM_ITERATIONS: 50_000
    RUN_VALIDATION: false
    DATA:
        PRELOADING_LEVEL: 0
        FIELDS: ['rgb', 'alpha']
        PRECOMPUTE_RAYS: true
        RAYS_TO_DEVICE: true
    BACKUP:
        FINAL_CHECKPOINT: true
        RENDER_TESTSET: true
        RENDER_TRAINSET: false
        RENDER_VALSET: false
        INTERMEDIATE_RENDERINGS: true
        VISUALIZE_ERRORS: false
        INTERVAL: -1
        TRAINING_STATE: false
    TIMING:
        ACTIVATE: true
        INCLUDE_DATALOADING_IN_TOTAL: false
        INCLUDE_PRETRAINING_IN_TOTAL: false
        INCLUDE_POSTTRAINING_IN_TOTAL: false
    WANDB:
        ACTIVATE: false
        ENTITY: null
        PROJECT: nerficg
        LOG_IMAGES: true
        INDEX_VALIDATION: -1
        INDEX_TRAINING: -1
        INTERVAL: 1000
        SWEEP_MODE:
            ACTIVE: false
            START_ITERATION: 999
            ITERATION_STRIDE: 1000
            NUM_IMAGES: -1
        VISUALIZE_OCCUPANCY_GRIDS: false
    WRITE_VRAM_STATS: false
    GUI:
        ACTIVATE: true
        RENDER_INTERVAL: 30
        GUI_STATUS_ENABLED: true
        GUI_STATUS_INTERVAL: 20
        SKIP_GUI_SETUP: false
        FPS_ROLLING_AVERAGE_SIZE: 100
    TARGET_BATCH_SIZE: 262_144
    WARMUP_STEPS: 256
    OCCUPANCY_GRID_UPDATE_INTERVAL: 16
    LR: 0.01
    LR_DECAY_START: 20_000
    LR_DECAY_INTERVAL: 10_000
    LR_DECAY_BASE: 0.33
DATASET:
    PATH: dataset/nerf_synthetic/lego
    IMAGE_SCALE_FACTOR: null
    NORMALIZE_CUBE: 2.6666666666666665  # NeRF synthetic cameras are inside [-4, 4]^3, geometry is only in the [-1.5, 1.5]^3
    NORMALIZE_RECENTER: false
    BACKGROUND_COLOR:
    - 0.0
    - 0.0
    - 0.0
    NEAR_PLANE: 2.0
    FAR_PLANE: 6.0
