GLOBAL:
    LOG_LEVEL: 2
    GPU_INDICES:
    - 0
    RANDOM_SEED: 0
    ANOMALY_DETECTION: false
    FILTER_WARNINGS: true
    METHOD_TYPE: NeRF
    DATASET_TYPE: NeRF
MODEL:
    HIERARCHICAL: true
    N_LAYERS: 8
    N_COLOR_LAYERS: 1
    N_FEATURES: 256
    N_FREQUENCIES_POSITION: 10
    N_FREQUENCIES_DIRECTION: 4
    ENCODING_APPEND_INPUT: true
    INPUT_SKIPS:
    - 5
    NETWORK_ACTIVATION: relu
RENDERER:
    RAY_BATCH_SIZE: 8_192
    N_SAMPLES: 256
    COARSE_RATIO: 0.25
TRAINING:
    LOAD_CHECKPOINT: null
    MODEL_NAME: nerf_lego
    NUM_ITERATIONS: 500_000
    RUN_VALIDATION: false
    DATA:
        PRELOADING_LEVEL: 0
        FIELDS: ['rgb', 'alpha']
        PRECOMPUTE_RAYS: true
        RAYS_TO_DEVICE: true
    BACKUP:
        FINAL_CHECKPOINT: true
        RENDER_TESTSET: true
        RENDER_TRAINSET: false
        RENDER_VALSET: false
        INTERMEDIATE_RENDERINGS: true
        VISUALIZE_ERRORS: false
        INTERVAL: -1
        TRAINING_STATE: false
    TIMING:
        ACTIVATE: false
        INCLUDE_DATALOADING_IN_TOTAL: true
        INCLUDE_PRETRAINING_IN_TOTAL: true
        INCLUDE_POSTTRAINING_IN_TOTAL: false
    WANDB:
        ACTIVATE: true
        ENTITY: null
        PROJECT: nerficg
        LOG_IMAGES: true
        INDEX_VALIDATION: -1
        INDEX_TRAINING: -1
        INTERVAL: 10_000
        SWEEP_MODE:
            ACTIVE: false
            START_ITERATION: 999
            ITERATION_STRIDE: 1000
            NUM_IMAGES: -1
    WRITE_VRAM_STATS: false
    BATCH_SIZE: 1024
    SAMPLE_SINGLE_IMAGE: true
    DENSITY_RANDOM_NOISE_STD: 0.0
    LR_INIT: 0.0005
    LR_FINAL: 0.00005
    LAMBDA_COLOR_LOSS: 1.0
    LAMBDA_ALPHA_LOSS: 0.0
DATASET:
    PATH: dataset/nerf_synthetic/lego
    IMAGE_SCALE_FACTOR: null
    NORMALIZE_CUBE: null
    NORMALIZE_RECENTER: false
    BACKGROUND_COLOR:
    - 1.0
    - 1.0
    - 1.0
    NEAR_PLANE: 2.0
    FAR_PLANE: 6.0
